//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hypotec.Web.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HypotecResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HypotecResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hypotec.Web.Utility.HypotecResource", typeof(HypotecResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string ConfirmationForChangePwd {
            get {
                return ResourceManager.GetString("ConfirmationForChangePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link has been sent to your email address, please check your email to reset your password..
        /// </summary>
        public static string ConfirmationForFgtPwd {
            get {
                return ResourceManager.GetString("ConfirmationForFgtPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully..
        /// </summary>
        public static string ConfirmationForResetPwd {
            get {
                return ResourceManager.GetString("ConfirmationForResetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hypotecmgld@gmail.com.
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found. You are not a registered user..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Please click the below link to reset your password.&lt;/b&gt;&lt;br/&gt;.
        /// </summary>
        public static string ForgetPasswordMsgBody {
            get {
                return ResourceManager.GetString("ForgetPasswordMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your changed password.
        /// </summary>
        public static string ForgetPasswordSubject {
            get {
                return ResourceManager.GetString("ForgetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successfully..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test@1234.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email id is not found..
        /// </summary>
        public static string ResetPasswordEmail {
            get {
                return ResourceManager.GetString("ResetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&apos;&gt;Reset Password&lt;/a&gt;.
        /// </summary>
        public static string ResetPasswordlink {
            get {
                return ResourceManager.GetString("ResetPasswordlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Failed. Please try again..
        /// </summary>
        public static string TokenFail {
            get {
                return ResourceManager.GetString("TokenFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not register..
        /// </summary>
        public static string UserNotRegister {
            get {
                return ResourceManager.GetString("UserNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User register successfully..
        /// </summary>
        public static string UserRegisterSuccess {
            get {
                return ResourceManager.GetString("UserRegisterSuccess", resourceCulture);
            }
        }
    }
}
