//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelocifyServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://service.leads360.com", ConfigurationName="VelocifyServiceReference.ClientServiceSoap")]
    public interface ClientServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentAsync(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgentToGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentToGroupAsync(string username, string password, System.Xml.XmlNode groupData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddAgentRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentRoleAsync(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddOptOut", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddOptOutAsync(string username, string password, string email, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddCampaignAsync(string username, string password, string title, string altTitle, int campaignTypeId, string note, decimal costPerLead, bool active, int providerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddField", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldAsync(string username, string password, string title, int fieldTypeId, string toolTip, bool required, int visibilityTypeId, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddFieldGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldGroupAsync(string username, string password, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeadAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadActionAsync(string username, string password, int leadId, int actionTypeId, string actionNote);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddLeadsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsExAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AddDirectMailLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AddDirectMailLeadsAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/DeactivateAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DeactivateAgentAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/DisableReceiveLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> DisableReceiveLeadsAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetActionTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetActionTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentAsync(string username, string password, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgentsInGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsInGroupAsync(string username, string password, int groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetAgentsQualified", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsQualifiedAsync(string username, string password, int programId, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetQualifiedAgents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetQualifiedAgentsAsync(string username, string password, int programId, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCallHistoryReport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCallHistoryReportAsync(string username, string password, string startDate, string endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetDistributionAuditLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetDistributionAuditLogAsync(string username, string password, string leadId, string callId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaigns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaignGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetCampaignTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetGroups", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetGroupsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLastCreatedLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastCreatedLeadAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLastModifiedLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastModifiedLeadAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAsync(string username, string password, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadFormTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadFormTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsAsync(string username, string password, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIdsEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsExAsync(string username, string password, System.DateTime from, System.DateTime to, int scope);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadIdsSpan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsSpanAsync(string username, string password, int fromNowMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsAsync(string username, string password, System.DateTime from, System.DateTime to);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsByPhone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByPhoneAsync(string username, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByEmailAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadsSpan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsSpanAsync(string username, string password, int fromNowMinutes);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetMilestones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetMilestonesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetPrograms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetProgramsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetProviders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetProvidersAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReportResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsAsync(string username, string password, int reportId, System.Xml.XmlNode templateValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReportResultsWithoutFilters", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsWithoutFiltersAsync(string username, string password, int reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetReports", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetServerTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetStatusesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetVisibilityTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetVisibilityTypesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentAsync(string username, string password, System.Xml.XmlNode agentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyAgentPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentPasswordAsync(string username, string password, string email, string agentPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadAgentAsync(string username, string password, int leadId, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadCampaignAsync(string username, string password, int leadId, int campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadField", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadFieldAsync(string username, string password, int leadId, int fieldId, string newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadsAsync(string username, string password, System.Xml.XmlNode leads);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifyLeadStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadStatusAsync(string username, string password, int leadId, int statusId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/RemoveCampaign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveCampaignAsync(string username, string password, int campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/RemoveLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveLeadAsync(string username, string password, int leadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/CopyLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> CopyLeadAsync(string username, string password, int LeadId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/AssignViaDistribution", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> AssignViaDistributionAsync(string username, string password, int leadId, int programId, int agentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadAndQualifiedAgentsByPhone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneAsync(string username, string password, string phone, int programId, int campaignId, int firstFieldId, string firstFieldValue, int secondFieldId, string secondFieldValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetLeadAndQualifiedAgentsByPhoneWithLead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneWithLeadAsync(string username, string password, string phone, int programId, int campaignId, VelocifyServiceReference.FieldValue[] fields);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldsSalesforce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsSalesforceAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldTypesSalesforce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesSalesforceAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetFieldGroupsSalesforce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsSalesforceAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetSalesforceMappings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetSalesforceMappingsAsync(string username, string sessionId, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifySalesforceMappings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceMappingsAsync(string username, string sessionId, string url, string xmlText);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/ModifySalesforceUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceUsernameAsync(string username, string password, string salesforceUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://service.leads360.com/GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetVersionAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://service.leads360.com")]
    public partial class FieldValue
    {
        
        private int fieldIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ClientServiceSoapChannel : VelocifyServiceReference.ClientServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ClientServiceSoapClient : System.ServiceModel.ClientBase<VelocifyServiceReference.ClientServiceSoap>, VelocifyServiceReference.ClientServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ClientServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ClientServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ClientServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ClientServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ClientServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentAsync(string username, string password, System.Xml.XmlNode agentData)
        {
            return base.Channel.AddAgentAsync(username, password, agentData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentToGroupAsync(string username, string password, System.Xml.XmlNode groupData)
        {
            return base.Channel.AddAgentToGroupAsync(username, password, groupData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddAgentRoleAsync(string username, string password, System.Xml.XmlNode agentData)
        {
            return base.Channel.AddAgentRoleAsync(username, password, agentData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddOptOutAsync(string username, string password, string email, int leadId)
        {
            return base.Channel.AddOptOutAsync(username, password, email, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddCampaignAsync(string username, string password, string title, string altTitle, int campaignTypeId, string note, decimal costPerLead, bool active, int providerId)
        {
            return base.Channel.AddCampaignAsync(username, password, title, altTitle, campaignTypeId, note, costPerLead, active, providerId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldAsync(string username, string password, string title, int fieldTypeId, string toolTip, bool required, int visibilityTypeId, int groupId)
        {
            return base.Channel.AddFieldAsync(username, password, title, fieldTypeId, toolTip, required, visibilityTypeId, groupId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddFieldGroupAsync(string username, string password, string title)
        {
            return base.Channel.AddFieldGroupAsync(username, password, title);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadActionAsync(string username, string password, int leadId, int actionTypeId, string actionNote)
        {
            return base.Channel.AddLeadActionAsync(username, password, leadId, actionTypeId, actionNote);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsAsync(string username, string password, System.Xml.XmlNode leads)
        {
            return base.Channel.AddLeadsAsync(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddLeadsExAsync(string username, string password, System.Xml.XmlNode leads)
        {
            return base.Channel.AddLeadsExAsync(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AddDirectMailLeadsAsync(string username, string password, System.Xml.XmlNode leads)
        {
            return base.Channel.AddDirectMailLeadsAsync(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DeactivateAgentAsync(string username, string password, string email)
        {
            return base.Channel.DeactivateAgentAsync(username, password, email);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> DisableReceiveLeadsAsync(string username, string password, string email)
        {
            return base.Channel.DisableReceiveLeadsAsync(username, password, email);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetActionTypesAsync(string username, string password)
        {
            return base.Channel.GetActionTypesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentAsync(string username, string password, int agentId)
        {
            return base.Channel.GetAgentAsync(username, password, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsAsync(string username, string password)
        {
            return base.Channel.GetAgentsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsInGroupAsync(string username, string password, int groupId)
        {
            return base.Channel.GetAgentsInGroupAsync(username, password, groupId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetAgentsQualifiedAsync(string username, string password, int programId, int leadId)
        {
            return base.Channel.GetAgentsQualifiedAsync(username, password, programId, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetQualifiedAgentsAsync(string username, string password, int programId, int leadId)
        {
            return base.Channel.GetQualifiedAgentsAsync(username, password, programId, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCallHistoryReportAsync(string username, string password, string startDate, string endDate)
        {
            return base.Channel.GetCallHistoryReportAsync(username, password, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetDistributionAuditLogAsync(string username, string password, string leadId, string callId)
        {
            return base.Channel.GetDistributionAuditLogAsync(username, password, leadId, callId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignsAsync(string username, string password)
        {
            return base.Channel.GetCampaignsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignGroupsAsync(string username, string password)
        {
            return base.Channel.GetCampaignGroupsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetCampaignTypesAsync(string username, string password)
        {
            return base.Channel.GetCampaignTypesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsAsync(string username, string password)
        {
            return base.Channel.GetFieldGroupsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsAsync(string username, string password)
        {
            return base.Channel.GetFieldsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesAsync(string username, string password)
        {
            return base.Channel.GetFieldTypesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetGroupsAsync(string username, string password)
        {
            return base.Channel.GetGroupsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastCreatedLeadAsync(string username, string password)
        {
            return base.Channel.GetLastCreatedLeadAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLastModifiedLeadAsync(string username, string password)
        {
            return base.Channel.GetLastModifiedLeadAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAsync(string username, string password, int leadId)
        {
            return base.Channel.GetLeadAsync(username, password, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadFormTypesAsync(string username, string password)
        {
            return base.Channel.GetLeadFormTypesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsAsync(string username, string password, System.DateTime from, System.DateTime to)
        {
            return base.Channel.GetLeadIdsAsync(username, password, from, to);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsExAsync(string username, string password, System.DateTime from, System.DateTime to, int scope)
        {
            return base.Channel.GetLeadIdsExAsync(username, password, from, to, scope);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadIdsSpanAsync(string username, string password, int fromNowMinutes)
        {
            return base.Channel.GetLeadIdsSpanAsync(username, password, fromNowMinutes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsAsync(string username, string password, System.DateTime from, System.DateTime to)
        {
            return base.Channel.GetLeadsAsync(username, password, from, to);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByPhoneAsync(string username, string password, string phone)
        {
            return base.Channel.GetLeadsByPhoneAsync(username, password, phone);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsByEmailAsync(string username, string password, string email)
        {
            return base.Channel.GetLeadsByEmailAsync(username, password, email);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadsSpanAsync(string username, string password, int fromNowMinutes)
        {
            return base.Channel.GetLeadsSpanAsync(username, password, fromNowMinutes);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetMilestonesAsync(string username, string password)
        {
            return base.Channel.GetMilestonesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetProgramsAsync(string username, string password)
        {
            return base.Channel.GetProgramsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetProvidersAsync(string username, string password)
        {
            return base.Channel.GetProvidersAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsAsync(string username, string password, int reportId, System.Xml.XmlNode templateValues)
        {
            return base.Channel.GetReportResultsAsync(username, password, reportId, templateValues);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportResultsWithoutFiltersAsync(string username, string password, int reportId)
        {
            return base.Channel.GetReportResultsWithoutFiltersAsync(username, password, reportId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetReportsAsync(string username, string password)
        {
            return base.Channel.GetReportsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetServerTimeAsync()
        {
            return base.Channel.GetServerTimeAsync();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetStatusesAsync(string username, string password)
        {
            return base.Channel.GetStatusesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetVisibilityTypesAsync(string username, string password)
        {
            return base.Channel.GetVisibilityTypesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentAsync(string username, string password, System.Xml.XmlNode agentData)
        {
            return base.Channel.ModifyAgentAsync(username, password, agentData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyAgentPasswordAsync(string username, string password, string email, string agentPassword)
        {
            return base.Channel.ModifyAgentPasswordAsync(username, password, email, agentPassword);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadAgentAsync(string username, string password, int leadId, int agentId)
        {
            return base.Channel.ModifyLeadAgentAsync(username, password, leadId, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadCampaignAsync(string username, string password, int leadId, int campaignId)
        {
            return base.Channel.ModifyLeadCampaignAsync(username, password, leadId, campaignId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadFieldAsync(string username, string password, int leadId, int fieldId, string newValue)
        {
            return base.Channel.ModifyLeadFieldAsync(username, password, leadId, fieldId, newValue);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadsAsync(string username, string password, System.Xml.XmlNode leads)
        {
            return base.Channel.ModifyLeadsAsync(username, password, leads);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifyLeadStatusAsync(string username, string password, int leadId, int statusId)
        {
            return base.Channel.ModifyLeadStatusAsync(username, password, leadId, statusId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveCampaignAsync(string username, string password, int campaignId)
        {
            return base.Channel.RemoveCampaignAsync(username, password, campaignId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RemoveLeadAsync(string username, string password, int leadId)
        {
            return base.Channel.RemoveLeadAsync(username, password, leadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> CopyLeadAsync(string username, string password, int LeadId)
        {
            return base.Channel.CopyLeadAsync(username, password, LeadId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> AssignViaDistributionAsync(string username, string password, int leadId, int programId, int agentId)
        {
            return base.Channel.AssignViaDistributionAsync(username, password, leadId, programId, agentId);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneAsync(string username, string password, string phone, int programId, int campaignId, int firstFieldId, string firstFieldValue, int secondFieldId, string secondFieldValue)
        {
            return base.Channel.GetLeadAndQualifiedAgentsByPhoneAsync(username, password, phone, programId, campaignId, firstFieldId, firstFieldValue, secondFieldId, secondFieldValue);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetLeadAndQualifiedAgentsByPhoneWithLeadAsync(string username, string password, string phone, int programId, int campaignId, VelocifyServiceReference.FieldValue[] fields)
        {
            return base.Channel.GetLeadAndQualifiedAgentsByPhoneWithLeadAsync(username, password, phone, programId, campaignId, fields);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldsSalesforceAsync(string username, string sessionId, string url)
        {
            return base.Channel.GetFieldsSalesforceAsync(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldTypesSalesforceAsync(string username, string sessionId, string url)
        {
            return base.Channel.GetFieldTypesSalesforceAsync(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetFieldGroupsSalesforceAsync(string username, string sessionId, string url)
        {
            return base.Channel.GetFieldGroupsSalesforceAsync(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetSalesforceMappingsAsync(string username, string sessionId, string url)
        {
            return base.Channel.GetSalesforceMappingsAsync(username, sessionId, url);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceMappingsAsync(string username, string sessionId, string url, string xmlText)
        {
            return base.Channel.ModifySalesforceMappingsAsync(username, sessionId, url, xmlText);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ModifySalesforceUsernameAsync(string username, string password, string salesforceUsername)
        {
            return base.Channel.ModifySalesforceUsernameAsync(username, password, salesforceUsername);
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://service.velocify.com/ClientService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ClientServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://service.velocify.com/ClientService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ClientServiceSoap,
            
            ClientServiceSoap12,
        }
    }
}
